#!/bin/sh

mysql_port=3306
mysql_username="root"
mysql_password="Kuihua*#816"

function_start_mysql()
{
    printf "Starting MySQL...\n"
    /bin/sh /weike/mysql/bin/mysqld_safe --defaults-file=/weike/mysql/etc/my.cnf 2>&1 > /dev/null &
}

function_stop_mysql()
{
    printf "Stoping MySQL...\n"
    /weike/mysql/bin/mysqladmin --default-character-set=utf8 -u ${mysql_username} -p${mysql_password} -S /tmp/mysql.sock shutdown
}

function_restart_mysql()
{
    printf "Restarting MySQL...\n"
    function_stop_mysql
    sleep 5
    function_start_mysql
}

if [ "$1" = "start" ]; then
    function_start_mysql
elif [ "$1" = "stop" ]; then
    function_stop_mysql
elif [ "$1" = "restart" ]; then
    function_restart_mysql
else
    printf "Usage: /weike/mysql/sbin/mysql {start stop restart}\n"
fi
